-- migrate:up
ALTER TABLE notes DROP COLUMN tags;

CREATE TYPE by_who AS ENUM ('user','ai');

-- creating tags table
CREATE TABLE tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    by_who by_who,
    tag TEXT,
    score INTEGER
);

-- linking table for notes and tags note_tags for mn reln

CREATE TABLE note_tags (
    note_id UUID,
    tag_id INTEGER,
    PRIMARY KEY (note_id, tag_id),
    FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags (id)
);


-- migrate:down

